#!/bin/bash

# fpp-plugin-santaslist install script

. ${FPPDIR}/scripts/common

# Self-locate: this script lives in <plugin>/scripts/, so its parent is the
# real install directory, whatever the folder is actually named on disk
# (a git clone or "Download ZIP" won't necessarily be named fpp-plugin-santaslist).
PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

mkdir -p /home/fpp/media/plugindata
chown fpp:fpp /home/fpp/media/plugindata

# Install the default cron.d schedule (every 2 minutes), pointed at wherever
# this plugin actually lives. The Settings page will rewrite this file if the
# refresh interval is changed later.
CRON_LINE="*/2 * * * * fpp /usr/bin/php ${PLUGIN_DIR}/cron/pull.php >/dev/null 2>&1"
echo "# Santa's List Hub - pulls fresh names from the hub on a schedule." > /tmp/santaslist-cron
echo "# Regenerated automatically when the refresh interval is changed in Settings." >> /tmp/santaslist-cron
echo "$CRON_LINE" >> /tmp/santaslist-cron
sudo cp /tmp/santaslist-cron /etc/cron.d/fpp-plugin-santaslist-cron
rm -f /tmp/santaslist-cron

chmod +x "${PLUGIN_DIR}/cron/pull.php"
chmod +x "${PLUGIN_DIR}/bin/display-daemon.php"
chmod +x "${PLUGIN_DIR}/bin/set-enabled.php"

# Install two tiny wrapper scripts into FPP's own scripts directory so they
# show up in the Scheduler's "Run Script" command picker -- this is how the
# display's on/off gets to be schedulable alongside regular playlists. FPP
# only looks in /home/fpp/media/scripts/ for these, not inside plugin dirs,
# so the actual logic still lives in the plugin and these just call into it.
mkdir -p /home/fpp/media/scripts
cat > /home/fpp/media/scripts/santaslist-enable.sh << EOF
#!/bin/bash
# Turns the Santa's List Hub display on. Generated by fpp-plugin-santaslist install.
/usr/bin/php ${PLUGIN_DIR}/bin/set-enabled.php 1
EOF
cat > /home/fpp/media/scripts/santaslist-disable.sh << EOF
#!/bin/bash
# Turns the Santa's List Hub display off. Generated by fpp-plugin-santaslist install.
/usr/bin/php ${PLUGIN_DIR}/bin/set-enabled.php 0
EOF
chmod +x /home/fpp/media/scripts/santaslist-enable.sh /home/fpp/media/scripts/santaslist-disable.sh
chown fpp:fpp /home/fpp/media/scripts/santaslist-enable.sh /home/fpp/media/scripts/santaslist-disable.sh

echo "Santa's List Hub plugin installed from ${PLUGIN_DIR}. Open Content Setup -> Santa's List Hub to configure it."
echo "To schedule it, use FPP's Scheduler with a 'Run Script' command: santaslist-enable.sh / santaslist-disable.sh"
